[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
metaplex_budget = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
metaplex_budget = "Hz5ZKTWQMRRcCGwMEjnqcQrLEkTp5E8qD2zZKPFxCmXf"

[programs.mainnet]
metaplex_budget = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/mnt/c/Users/Dom/Documents/xxDev/GhostLabs/metadao/MD_Bx/subzns-keypair-tn.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


